[theme]

# Blue
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#C6CDD4"
font = "sans serif"


# Dark
#primaryColor="#FF7903"
#backgroundColor="#0E1117"
#secondaryBackgroundColor="#31333F"
#textColor="#FAFAFA"
#font="sans serif"

[server]
maxUploadSize=514